// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNcWTrh_3q_R818CJxTeHRpGBaXUBeJsM',
    appId: '1:268166694444:web:d4198d12be1c380373b389',
    messagingSenderId: '268166694444',
    projectId: 'dailyreminderapp-eedf3',
    authDomain: 'dailyreminderapp-eedf3.firebaseapp.com',
    storageBucket: 'dailyreminderapp-eedf3.appspot.com',
    measurementId: 'G-GFXDEZPK4S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB--CExbAPwYB-lcZbMRg1X7AQOQxXGrQw',
    appId: '1:268166694444:android:48d064932a49d95d73b389',
    messagingSenderId: '268166694444',
    projectId: 'dailyreminderapp-eedf3',
    storageBucket: 'dailyreminderapp-eedf3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZv3XplQIkZDl_jHosVp3iMYoYhHXQtDk',
    appId: '1:268166694444:ios:374d3109a0bacf4373b389',
    messagingSenderId: '268166694444',
    projectId: 'dailyreminderapp-eedf3',
    storageBucket: 'dailyreminderapp-eedf3.appspot.com',
    iosBundleId: 'com.example.flutterToDoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZv3XplQIkZDl_jHosVp3iMYoYhHXQtDk',
    appId: '1:268166694444:ios:c906c5b8602d002173b389',
    messagingSenderId: '268166694444',
    projectId: 'dailyreminderapp-eedf3',
    storageBucket: 'dailyreminderapp-eedf3.appspot.com',
    iosBundleId: 'com.example.flutterToDoList.RunnerTests',
  );
}
